add login
filippovskii09/chat-new pull request #1
Opened 2024-04-08 11:14 UTC by filippovskii09

2024-04-08 11:16 UTC, filippovskii09 commented
Add login button

2024-04-08 12:08 UTC, KozlovAndrii requested changes

2024-04-08 12:08 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +	console.log(user);
Remove rudundant console.log(...)

2024-04-08 12:08 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +	const generateRandomUser = () => {
Extract this function to .../common/utils (or helpers)

2024-04-08 12:08 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +			<button className={styles.button} onClick={() => generateRandomUser()}>Start chating</button>
".button" styles does not exist in `Login.module.scss` file.
Either add this style of remove `className={styles.button}`

2024-04-08 12:08 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +	const [user, setUser] = useState<User>({
useState<User | null>
Default value should be null

2024-04-08 12:08 UTC, KozlovAndrii commented on src/app/page.tsx
>  const page = () => {
It should HomePage

2024-04-08 12:08 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +	const [user, setUser] = useState<User>({
You don't need this user state, because you already use localstorage to store your user

2024-04-08 12:21 UTC, KozlovAndrii commented on components/Login/Login.tsx
> +		<section className={styles.login}>
Remove section.
Rename component to LoginButton.

2024-04-08 12:23 UTC, KozlovAndrii requested changes

2024-04-08 12:23 UTC, KozlovAndrii commented on src/app/page.tsx
> +			<Login/>
You should remove <section> from <Login> component and rename <Login> to <LoginButton>.

Move page.tsx to its own folder - src/app/(home)/page.tsx
Create HomePage.modules.scss

And style you page in this .scss file

2024-04-09 07:15 UTC, KozlovAndrii requested changes

2024-04-09 07:15 UTC, KozlovAndrii commented on common/utils/loginUtils.ts
> +export const generateRandomUser = () => {
Those a not loginUtils.ts

it is generateRandomUser.ts or generateRandomUser.util.ts

2024-04-09 07:15 UTC, KozlovAndrii commented on common/utils/loginUtils.ts
> +	return {name: randomName, id: uuid()}
return { id: uuid(), name: names[Math.floor(Math.random() * names.length)] }

2024-04-09 07:15 UTC, KozlovAndrii commented on src/app/globals.scss
>  	width: 100%;
You have to many redundant classes in this file. 

For reset styles you would normally use reset.scss and you would import reset.scss in global.scss

https://stackoverflow.com/questions/11578819/css-reset-what-exactly-does-it-do

2024-04-09 07:15 UTC, KozlovAndrii commented on common/utils/loginUtils.ts
> +export const generateRandomUser = () => {
or generate-random-user.ts or generate_random_user.ts

2024-04-09 07:30 UTC, KozlovAndrii requested changes

2024-04-09 07:30 UTC, KozlovAndrii commented on common/utils/generateRandomUser.util.ts
> +
Empty line

2024-04-09 07:30 UTC, KozlovAndrii commented on src/app/globals.scss
> +@import './reset.scss';
Create folder styles in /src and store globals.scss and reset.scss there

2024-04-09 08:03 UTC, merged